### ISSUE TITLE
Updating the theme

### ISSUE THREAD

**Issue by kevindstevens1010** [aravindballa/gatsby-theme-andy#21]
What's the best way to update the theme as you work on updates?

**Comment by kevindstevens1010** [comment]
Note: I updated the BrainNote.Js file and am now getting this error which is why I ask:

There was an error in your GraphQL query:

Cannot query field "inboundReferencePreviews" on type "BrainNote".

If you don't expect "inboundReferencePreviews" to exist on the type "BrainNote" it is most likely a typo.
However, if you expect "inboundReferencePreviews" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "inboundReferencePreviews" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "BrainNote":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/www/my-gatsby-garden/node_modules/@aengusm/gatsby-theme-brain/src/templates/brain.js

**Comment by aravindballa** [comment]
Hey!

I try to publish a new package to npm with a new version whenever something gets updated or fixed in the package. So, a `yarn install` or `npm install` should get you the new version. Sometimes deleting the `node_modules` directory and installing gets latest versions.

Regarding that error, can you check which version of Node you are using? We would need at least v12 to run this.

**Comment by kevindstevens1010** [comment]
Still not working after deleting node modules and bringing them back in. 

I'm running Node v.14.5.0

**Comment by aravindballa** [comment]
> Note: I updated the BrainNote.Js file and am now getting this error which is why I ask ...

Where does this file exist in your repo? And is it possible to share the code somehow?

**Comment by kevindstevens1010** [comment]
Of course, here's the path:

/my-gatsby-garden/node_modules/@aengusm/gatsby-theme-brain/src/components/BrainNote.js

And here's the code in BrainNote.js

`import React from "react";
import MDXRenderer from "gatsby-plugin-mdx/mdx-renderer";

const BrainNote = ({ note }) => {
  let references = [];
  let referenceBlock;
  if (note.inboundReferencePreviews != null) {
    references = note.inboundReferencePreviews.map((ref) => (
      <li>
        <a href={ref.source}>{ref.source}</a>
        <br />
        <div dangerouslySetInnerHTML={{ __html: ref.previewHtml }} />
      </li>
    ));

    if (references.length > 0) {
      referenceBlock = (
        <>
          <h2>Linked References</h2>
          <ul>{references}</ul>
        </>
      );
    }
  }

  let externalRefBlock = [];
  if (note.externalInboundReferences !== null) {
    let refs = note.externalInboundReferences.map((ref) => (
      <li>
        <a href={ref.sourceUrl}>
          {ref.siteName}/{ref.sourcePage}
        </a>
        <br />
        <div dangerouslySetInnerHTML={{ __html: ref.previewHtml }} />
      </li>
    ));
    if (refs.length > 0) {
      externalRefBlock = (
        <>
          <h2>External References</h2>
          <ul>{refs}</ul>
        </>
      );
    }
  }
  return (
    <div id="brainNote">
      <h1>{note.title}</h1>
      <MDXRenderer>{note.childMdx.body}</MDXRenderer>
      {referenceBlock}
      {externalRefBlock}
    </div>
  );
};

export default BrainNote;
`

**Comment by aravindballa** [comment]
We don't ideally touch/change things in the `node_modules` folder. What is the result you are aiming for?

We can use component shadowing to update the components as we like. More about that [here](https://github.com/aravindballa/gatsby-theme-andy#shadowing-components). Basically we place a file at the respective path in our project, and this file overwrites the original file in `node_modules`. For example, if you want to change `node_modules/gatsby-theme-andy/src/components/BrainNote.js`, we create a file at `src/gatsby-theme-andy/components/BrainNote.js`.
